import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


GLYPHS = "!()+./0123456789?EFJKSacenprt간게고기끄나남누는니다도동둘드들라로르를만먹면모몰무버빠빼사수시아안압얻온으은임자작전점종중창척체최컴켰킨킴쿵터텼퓨하화히"
COLORS = ((245, 240, 220), (255, 185, 55), (105, 205, 160), (12, 15, 20))
MAGENTA = (255, 0, 255)
CELL = (16, 20)
FONT_SIZE = 17
COLS = 32
ROWS_PER_BANK = 3


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the PF Stardust bitmap glyph atlas.")
    parser.add_argument("--font", required=True, type=Path, help="Licensed PF Stardust font file")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "assets/font_atlas.png",
    )
    parser.add_argument(
        "--header",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "font_atlas_data.h",
    )
    args = parser.parse_args()

    if len(GLYPHS) > COLS * ROWS_PER_BANK:
        raise ValueError("font atlas capacity exceeded")

    font = ImageFont.truetype(args.font, FONT_SIZE)
    ascent, descent = font.getmetrics()
    baseline_y = (CELL[1] - ascent - descent) // 2
    widths = [font.getbbox(glyph)[2] - font.getbbox(glyph)[0] for glyph in GLYPHS]
    if max(widths) > CELL[0]:
        raise ValueError("font glyph exceeds atlas cell width")
    atlas = Image.new("RGB", (512, CELL[1] * ROWS_PER_BANK * len(COLORS)), MAGENTA)
    for bank, color in enumerate(COLORS):
        for index, glyph in enumerate(GLYPHS):
            mask = Image.new("L", CELL, 0)
            draw = ImageDraw.Draw(mask)
            bounds = draw.textbbox((0, 0), glyph, font=font)
            x = -bounds[0]
            draw.text((x, baseline_y), glyph, font=font, fill=255)
            mask = mask.point(lambda value: 255 if value >= 128 else 0)
            slot_x = (index % COLS) * CELL[0]
            slot_y = bank * ROWS_PER_BANK * CELL[1] + (index // COLS) * CELL[1]
            tile = Image.new("RGB", CELL, color)
            atlas.paste(tile, (slot_x, slot_y), mask)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    atlas.save(args.output, optimize=True)
    args.header.write_text(
        "/* Generated by tools/build_font_atlas.py from PF Stardust Regular. */\n"
        f"static const wchar_t font_chars[]=L\"{GLYPHS}\";\n"
        f"static const unsigned char font_widths[]={{{','.join(map(str, widths))}}};\n"
        f"static const unsigned char font_space_width={round(font.getlength(' '))};\n",
        encoding="utf-8",
    )
    assert atlas.size == (512, 240)


if __name__ == "__main__":
    main()
