/* Generated by tools/build_font_atlas.py from PF Stardust Regular. */
static const wchar_t font_chars[]=L"!()+./0123456789?EFJKSacenprt간게고기끄나남누는니다도동둘드들라로르를만먹면모몰무버빠빼사수시아안압얻온으은임자작전점종중창척체최컴켰킨킴쿵터텼퓨하화히";
static const unsigned char font_widths[]={7,7,7,15,5,8,10,10,10,10,10,10,10,10,10,10,10,13,13,13,13,13,12,10,10,10,10,8,8,16,16,15,16,15,16,16,15,15,16,16,15,15,15,15,15,16,15,15,15,16,16,16,15,15,15,16,16,16,16,15,16,16,16,16,16,15,15,15,16,16,16,16,16,15,15,16,16,16,16,16,16,16,16,15,16,16,15,16,16,16};
static const unsigned char font_space_width=9;
