typedef void* H; typedef H HWND; typedef H HDC; typedef H HINSTANCE; typedef H HGDIOBJ; typedef H HBRUSH; typedef H HPEN; typedef H HFONT; typedef H HBITMAP; typedef const wchar_t* W;
typedef unsigned int U; typedef unsigned long D,C; typedef unsigned long long WP,UP; typedef long long LP,LR; typedef int B; typedef unsigned short A;
extern "C" int _fltused=0; extern "C" void* memset(void* p,int v,unsigned long long n){unsigned char* b=(unsigned char*)p;while(n--)*b++=(unsigned char)v;return p;}
struct RECT{long left,top,right,bottom;}; struct POINT{long x,y;}; union LI{struct{unsigned long lo;long hi;};long long q;};
struct PS{HDC dc;B erase;RECT r;B restore,inc;unsigned char pad[32];}; struct MSG{HWND w;U m;WP wp;LP lp;D time;POINT p;D priv;};
typedef LR(__stdcall* PROC)(HWND,U,WP,LP); struct WC{U style;PROC proc;int ce,we;HINSTANCE ins;H icon,cursor;HBRUSH bg;W menu,name;};
extern "C"{
__declspec(dllimport)B __stdcall QueryPerformanceCounter(LI*);__declspec(dllimport)B __stdcall QueryPerformanceFrequency(LI*);__declspec(dllimport)HINSTANCE __stdcall GetModuleHandleW(W);__declspec(dllimport)wchar_t* __stdcall GetCommandLineW();__declspec(dllimport)void __stdcall ExitProcess(U);
__declspec(dllimport)A __stdcall RegisterClassW(const WC*);__declspec(dllimport)HWND __stdcall CreateWindowExW(D,W,W,D,int,int,int,int,HWND,H,HINSTANCE,void*);__declspec(dllimport)B __stdcall AdjustWindowRect(RECT*,D,B);__declspec(dllimport)B __stdcall ShowWindow(HWND,int);__declspec(dllimport)B __stdcall GetMessageW(MSG*,HWND,U,U);__declspec(dllimport)B __stdcall TranslateMessage(const MSG*);__declspec(dllimport)LR __stdcall DispatchMessageW(const MSG*);__declspec(dllimport)LR __stdcall DefWindowProcW(HWND,U,WP,LP);__declspec(dllimport)void __stdcall PostQuitMessage(int);__declspec(dllimport)UP __stdcall SetTimer(HWND,UP,U,void*);__declspec(dllimport)B __stdcall InvalidateRect(HWND,const RECT*,B);__declspec(dllimport)HWND __stdcall SetCapture(HWND);__declspec(dllimport)B __stdcall ReleaseCapture();__declspec(dllimport)H __stdcall LoadCursorW(HINSTANCE,W);__declspec(dllimport)H __stdcall LoadIconW(HINSTANCE,W);__declspec(dllimport)B __stdcall GetClientRect(HWND,RECT*);__declspec(dllimport)HDC __stdcall BeginPaint(HWND,PS*);__declspec(dllimport)B __stdcall EndPaint(HWND,const PS*);__declspec(dllimport)int __stdcall FillRect(HDC,const RECT*,HBRUSH);
__declspec(dllimport)HDC __stdcall CreateCompatibleDC(HDC);__declspec(dllimport)HBITMAP __stdcall CreateCompatibleBitmap(HDC,int,int);__declspec(dllimport)HGDIOBJ __stdcall SelectObject(HDC,HGDIOBJ);__declspec(dllimport)B __stdcall DeleteObject(HGDIOBJ);__declspec(dllimport)B __stdcall DeleteDC(HDC);__declspec(dllimport)HBRUSH __stdcall CreateSolidBrush(C);__declspec(dllimport)HPEN __stdcall CreatePen(int,int,C);__declspec(dllimport)B __stdcall RoundRect(HDC,int,int,int,int,int,int);__declspec(dllimport)B __stdcall MoveToEx(HDC,int,int,POINT*);__declspec(dllimport)B __stdcall LineTo(HDC,int,int);__declspec(dllimport)B __stdcall Ellipse(HDC,int,int,int,int);__declspec(dllimport)HFONT __stdcall CreateFontW(int,int,int,int,int,D,D,D,D,D,D,D,D,W);__declspec(dllimport)int __stdcall SetBkMode(HDC,int);__declspec(dllimport)C __stdcall SetTextColor(HDC,C);__declspec(dllimport)B __stdcall TextOutW(HDC,int,int,W,int);__declspec(dllimport)B __stdcall BitBlt(HDC,int,int,int,int,HDC,int,int,D);
}
#define RGB(r,g,b) ((C)((r)|((g)<<8)|((b)<<16)))
#define DOWN 513
struct Meat{float x,y,c[2];int side;};static Meat meat[5];static int held=-1,gx,gy,score,streak;static float left;static LI tick,freq;static const RECT grill={210,120,690,500},plate={745,205,915,410};
static int len(W s){int n=0;while(s[n])n++;return n;}static int min(int a,int b){return a<b?a:b;}static int max(int a,int b){return a>b?a:b;}static float fmin(float a,float b){return a<b?a:b;}static int in(const RECT&r,float x,float y){return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;}static int good(const Meat&m){return m.c[0]>=3&&m.c[0]<=7&&m.c[1]>=3&&m.c[1]<=7;}
static void resetOne(int i){meat[i].x=75.0f+(i%2)*70;meat[i].y=180.0f+(i/2)*105;meat[i].c[0]=meat[i].c[1]=0;meat[i].side=0;}static void reset(){for(int i=0;i<5;i++)resetOne(i);held=-1;score=streak=0;left=60;QueryPerformanceCounter(&tick);}
static C color(float c){return c<1.5f?RGB(225,105,110):c<3?RGB(202,112,74):c<=7?RGB(139,76,43):RGB(45,34,29);}static void fill(HDC dc,const RECT&r,C c){HBRUSH b=CreateSolidBrush(c);FillRect(dc,&r,b);DeleteObject(b);}static void txt(HDC dc,int x,int y,int s,W z){HFONT f=CreateFontW(s,0,0,0,700,0,0,0,129,0,0,4,0,L"Malgun Gothic");HGDIOBJ o=SelectObject(dc,f);SetBkMode(dc,1);SetTextColor(dc,RGB(255,245,222));TextOutW(dc,x,y,z,len(z));SelectObject(dc,o);DeleteObject(f);}
static wchar_t* ap(wchar_t*p,W s){while(*s)*p++=*s++;return p;}static wchar_t* num(wchar_t*p,int n){wchar_t t[16];int k=0;if(!n){*p++=48;return p;}while(n){t[k++]=(wchar_t)(48+n%10);n/=10;}while(k)*p++=t[--k];return p;}static void hud(wchar_t*z){wchar_t*p=z;p=ap(p,L"점수 ");p=num(p,score);p=ap(p,L"   콤보 ");p=num(p,streak);p=ap(p,L"   시간 ");p=num(p,max(0,(int)(left+.99f)));*p=0;}
static void steak(HDC dc,const Meat&m,int sel){int x=(int)m.x,y=(int)m.y;HBRUSH b=CreateSolidBrush(color(m.c[m.side]));HPEN p=CreatePen(0,sel?5:2,sel?RGB(255,225,80):RGB(91,39,28));HGDIOBJ ob=SelectObject(dc,b),op=SelectObject(dc,p);RoundRect(dc,x-31,y-23,x+31,y+23,18,18);SelectObject(dc,op);SelectObject(dc,ob);DeleteObject(p);DeleteObject(b);for(int i=0;i<3;i++){int q=x-17+i*16;HPEN a=CreatePen(0,3,RGB(78,47,33));HGDIOBJ o=SelectObject(dc,a);MoveToEx(dc,q-5,y-12,0);LineTo(dc,q+5,y+12);SelectObject(dc,o);DeleteObject(a);}for(int s=0;s<2;s++){RECT r={x-31,y+29+s*7,x+31,y+34+s*7};fill(dc,r,RGB(55,48,42));r.right=r.left+(long)(62*fmin(m.c[s]/8,1));fill(dc,r,m.c[s]<3?RGB(235,99,105):m.c[s]<=7?RGB(91,205,105):RGB(30,25,23));}}
static void paint(HWND w){PS ps={};HDC out=BeginPaint(w,&ps);RECT cl;GetClientRect(w,&cl);HDC dc=CreateCompatibleDC(out);HBITMAP bm=CreateCompatibleBitmap(out,cl.right,cl.bottom);HGDIOBJ old=SelectObject(dc,bm);fill(dc,cl,RGB(35,31,27));RECT top={0,0,cl.right,82};fill(dc,top,RGB(117,39,31));txt(dc,28,18,34,L"집게는 내가 잡는다!");wchar_t z[100];hud(z);txt(dc,525,25,22,z);RECT tray={25,125,180,510};fill(dc,tray,RGB(102,119,126));txt(dc,54,92,22,L"생고기");fill(dc,grill,RGB(72,68,62));HPEN gr=CreatePen(0,5,RGB(31,30,28));HGDIOBJ po=SelectObject(dc,gr);for(int x=228;x<690;x+=24){MoveToEx(dc,x,120,0);LineTo(dc,x,500);}SelectObject(dc,po);DeleteObject(gr);txt(dc,405,91,22,L"불판");HBRUSH pb=CreateSolidBrush(RGB(236,229,207));HGDIOBJ bo=SelectObject(dc,pb);HPEN pp=CreatePen(0,8,RGB(165,191,200));po=SelectObject(dc,pp);Ellipse(dc,plate.left,plate.top,plate.right,plate.bottom);SelectObject(dc,po);SelectObject(dc,bo);DeleteObject(pp);DeleteObject(pb);txt(dc,786,170,22,L"접시");for(int i=0;i<5;i++)steak(dc,meat[i],i==held);txt(dc,30,540,20,L"왼쪽 드래그: 옮기기     오른쪽 클릭: 뒤집기     R: 재시작");txt(dc,30,575,18,L"양쪽 막대가 초록색일 때 접시에 놓으세요.");if(left<=0){RECT sh={180,225,750,390};fill(dc,sh,RGB(80,25,22));txt(dc,355,245,44,L"영업 끝!");wchar_t q[40],*p=q;p=ap(p,L"최종 점수  ");p=num(p,score);*p=0;txt(dc,375,310,30,q);txt(dc,370,350,18,L"R을 누르면 다시 시작");}BitBlt(out,0,0,cl.right,cl.bottom,dc,0,0,0xCC0020);SelectObject(dc,old);DeleteObject(bm);DeleteDC(dc);EndPaint(w,&ps);}
static int xx(LP l){return(short)(l&65535);}static int yy(LP l){return(short)((l>>16)&65535);}static int hit(int x,int y){for(int i=4;i>=0;i--)if(x-meat[i].x<35&&meat[i].x-x<35&&y-meat[i].y<28&&meat[i].y-y<28)return i;return-1;}
static LR __stdcall proc(HWND w,U m,WP a,LP l){if(m==275){LI now;QueryPerformanceCounter(&now);float dt=(float)(now.q-tick.q)/(float)freq.q;tick=now;if(left>0){left-=fmin(dt,.1f);for(int i=0;i<5;i++)if(i!=held&&in(grill,meat[i].x,meat[i].y))meat[i].c[meat[i].side]+=dt;}InvalidateRect(w,0,0);return 0;}if(m==DOWN){if(left<=0)return 0;held=hit(xx(l),yy(l));if(held>=0){gx=xx(l)-(int)meat[held].x;gy=yy(l)-(int)meat[held].y;SetCapture(w);}return 0;}if(m==512&&held>=0&&(a&1)){meat[held].x=(float)max(32,min(928,xx(l)-gx));meat[held].y=(float)max(108,min(500,yy(l)-gy));InvalidateRect(w,0,0);return 0;}if(m==514&&held>=0){int i=held;held=-1;ReleaseCapture();if(in(plate,meat[i].x,meat[i].y)){if(good(meat[i])){score+=100+streak*15;streak++;}else{score=max(0,score-30);streak=0;}resetOne(i);}InvalidateRect(w,0,0);return 0;}if(m==516){int i=hit(xx(l),yy(l));if(i>=0&&left>0)meat[i].side^=1;InvalidateRect(w,0,0);return 0;}if(m==256){if(a=='R')reset();return 0;}if(m==15){paint(w);return 0;}if(m==20)return 1;if(m==2){PostQuitMessage(0);return 0;}return DefWindowProcW(w,m,a,l);}
static int contains(W s,W n){for(int i=0;s[i];i++){int j=0;while(n[j]&&s[i+j]==n[j])j++;if(!n[j])return 1;}return 0;}static int test(){Meat m={0,0,{3,7},0};if(!good(m))return 1;m.c[1]=2.9f;if(good(m))return 2;m.c[1]=7.1f;return good(m)?3:0;}
static int run(){if(contains(GetCommandLineW(),L"--self-test"))return test();QueryPerformanceFrequency(&freq);HINSTANCE ins=GetModuleHandleW(0);WC wc={};wc.proc=proc;wc.ins=ins;wc.cursor=LoadCursorW(0,(W)32649);wc.icon=LoadIconW(0,(W)32512);wc.name=L"TongsGame";if(!RegisterClassW(&wc))return 1;RECT r={0,0,960,620};D style=0xCA0000;AdjustWindowRect(&r,style,0);HWND w=CreateWindowExW(0,wc.name,L"집게는 내가 잡는다!",style,(int)0x80000000,(int)0x80000000,r.right-r.left,r.bottom-r.top,0,0,ins,0);if(!w)return 2;reset();SetTimer(w,1,16,0);ShowWindow(w,1);MSG msg;while(GetMessageW(&msg,0,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return(int)msg.wp;}
extern "C" void mainCRTStartup(){ExitProcess((U)run());}
